version: '3.8'

services:
  postgres:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

  frontend:
    image: raikhert/foodgramfront:latest
    volumes:
      - frontend_data:/app/result_build/
    depends_on:
      - postgres
  backend:
    image: raikhert/foodgramback:latest
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
  migrations:
    image: raikhert/foodgramback:latest
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    command: bash -c
            "python3 manage.py migrate &&
             python3 manage.py collectstatic &&
             python3 manage.py createadmin &&
             python3 manage.py filldb"
    depends_on:
      - backend
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/redoc.html:/usr/share/nginx/html/foodgram/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/foodgram/docs/openapi-schema.yml
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - postgres
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_data:
  static_value:
  media_value:
