# Generated by Django 3.2.5 on 2021-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210916_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredientitem',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_item'),
        ),
    ]
